### ISSUE TITLE
panic in reconciler (randomsecret)

### ISSUE THREAD

**Issue by MrLuje** [redhat-cop/vault-config-operator#102]
Operator is CrashLoopBackOff with following log :

```log
1.672906904078972e+09    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference    {"controller": "randomsecret", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "RandomSecret", "RandomSecret": {"name":"my-postgresql-admin-password-geocoding","namespace":"geocoding-dev"}, "namespace": "geocoding-dev", "name": "my-postgresql-admin-password-geocoding", "reconcileID": "e575cc8a-daed-4224-a140-22201b27083b"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1684d94]

goroutine 1001 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x186b320, 0x2a566a0})
    /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*RandomSecret).GenerateNewPassword(0xc0014ae540, {0x1d634c8?, 0xc00323c450?})
    /home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/randomsecret_types.go:204 +0xd4
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*RandomSecret).PrepareInternalValues(...)
    /home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/randomsecret_types.go:112
github.com/redhat-cop/vault-config-operator/controllers.(*RandomSecretReconciler).manageReconcileLogic(0xc000550ee0, {0x1d634c8, 0xc00323c450}, 0xc0014ae540)
    /home/runner/work/vault-config-operator/vault-config-operator/controllers/randomsecret_controller.go:142 +0x13e
github.com/redhat-cop/vault-config-operator/controllers.(*RandomSecretReconciler).Reconcile(0xc000550ee0, {0x1d634c8, 0xc00163fa40}, {{{0xc0021a0100?, 0x10?}, {0xc0015032f0?, 0x40f687?}}})
    /home/runner/work/vault-config-operator/vault-config-operator/controllers/randomsecret_controller.go:107 +0x68a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1d63420?, {0x1d634c8?, 0xc00163fa40?}, {{{0xc0021a0100?, 0x19b9b80?}, {0xc0015032f0?, 0x405094?}}})
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00032f9a0, {0x1d63420, 0xc0013f8c40}, {0x18d33c0?, 0xc002164000?})
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00032f9a0, {0x1d63420, 0xc0013f8c40})
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
Stream closed EOF for vault-admin-dev/vault-config-operator-dev-5f4bf54485-j5fvc (vault-config-operator)
```

I think it happened because I removed the vault_password_policy after creating the RandomSecret, and make it fails at next refresh

**Comment by raffaelespazzoli** [comment]
ok, it shouldn't panic, but it should error out. thanks for pointing this out.

**Comment by tmmorin** [comment]
hello 

I have seen a very similar issue, if not the same, happen with the very recent `v0.8.15`:

```
$ kubectl -n vault logs vault-config-operator-58dc6585c-5vswq vault-config-operator --previous | tail -40     
1.6855192608474915e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-redhatcop-redhat-io-v1alpha1-randomsecret", "UID": "fecd917e-a863-49ba-a008-eb8bbf8ca608", "kind": "redhatcop.redhat.io/v1alpha1, Kind=RandomSecret", "resource": {"group":"redhatcop.redhat.io","version":"v1alpha1","resource":"randomsecrets"}}
1.6855192608476207e+09	INFO	randomsecret-resource	validate create	{"name": "keycloak"}
1.685519260847698e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-redhatcop-redhat-io-v1alpha1-randomsecret", "code": 200, "reason": "", "UID": "fecd917e-a863-49ba-a008-eb8bbf8ca608", "allowed": true}
1.6855192608663385e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-redhatcop-redhat-io-v1alpha1-passwordpolicy", "UID": "283137cb-cbcd-4a22-acd1-23e310ffb87c", "kind": "redhatcop.redhat.io/v1alpha1, Kind=PasswordPolicy", "resource": {"group":"redhatcop.redhat.io","version":"v1alpha1","resource":"passwordpolicies"}}
1.6855192608665023e+09	INFO	passwordpolicy-resource	default	{"name": "sylva-password-policy"}
1.6855192608667333e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-redhatcop-redhat-io-v1alpha1-passwordpolicy", "code": 200, "reason": "", "UID": "283137cb-cbcd-4a22-acd1-23e310ffb87c", "allowed": true}
1.6855192608902764e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-redhatcop-redhat-io-v1alpha1-randomsecret", "UID": "6ef6ec35-9428-43c5-aeb7-a97108a3f404", "kind": "redhatcop.redhat.io/v1alpha1, Kind=RandomSecret", "resource": {"group":"redhatcop.redhat.io","version":"v1alpha1","resource":"randomsecrets"}}
1.68551926089047e+09	INFO	authenginemount-resource	default	{"name": "keycloak"}
1.685519260890826e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-redhatcop-redhat-io-v1alpha1-randomsecret", "code": 200, "reason": "", "UID": "6ef6ec35-9428-43c5-aeb7-a97108a3f404", "allowed": true}
1.6855192608929632e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-redhatcop-redhat-io-v1alpha1-randomsecret", "UID": "15e99c86-e62e-4bfb-b376-22e92b7f3d21", "kind": "redhatcop.redhat.io/v1alpha1, Kind=RandomSecret", "resource": {"group":"redhatcop.redhat.io","version":"v1alpha1","resource":"randomsecrets"}}
1.685519260893182e+09	INFO	randomsecret-resource	validate create	{"name": "keycloak"}
1.6855192608932166e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-redhatcop-redhat-io-v1alpha1-randomsecret", "code": 200, "reason": "", "UID": "15e99c86-e62e-4bfb-b376-22e92b7f3d21", "allowed": true}
1.685519260982153e+09	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "randomsecret", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "RandomSecret", "RandomSecret": {"name":"keycloak","namespace":"vault"}, "namespace": "vault", "name": "keycloak", "reconcileID": "0f888a32-c58c-46f3-96da-876db0a0e4a7"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1686e58]

goroutine 1065 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x18709c0, 0x2a5f760})
	/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*RandomSecret).GenerateNewPassword(0xc000acc000, {0x1d69f08?, 0xc0015846c0?})
	/home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/randomsecret_types.go:212 +0xd8
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*RandomSecret).PrepareInternalValues(...)
	/home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/randomsecret_types.go:120
github.com/redhat-cop/vault-config-operator/controllers.(*RandomSecretReconciler).manageReconcileLogic(0xc000679260, {0x1d69f08, 0xc0015846c0}, 0xc000acc000)
	/home/runner/work/vault-config-operator/vault-config-operator/controllers/randomsecret_controller.go:144 +0x13e
github.com/redhat-cop/vault-config-operator/controllers.(*RandomSecretReconciler).Reconcile(0xc000679260, {0x1d69f08, 0xc001305170}, {{{0xc000caa570?, 0x10?}, {0xc000caa568?, 0x40f687?}}})
	/home/runner/work/vault-config-operator/vault-config-operator/controllers/randomsecret_controller.go:108 +0x459
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1d69e60?, {0x1d69f08?, 0xc001305170?}, {{{0xc000caa570?, 0x19bfb80?}, {0xc000caa568?, 0x405094?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000375860, {0x1d69e60, 0xc0002bfd00}, {0x18d8c80?, 0xc000762200?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000375860, {0x1d69e60, 0xc0002bfd00})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333

```

the trace ends at the line modified by the fix for this isse:
```
        if d.Spec.SecretFormat.PasswordPolicyName != "" {
                vaultClient := context.Value("vaultClient").(*vault.Client)
                response, err := vaultClient.Logical().Read("/sys/policies/password/" + d.Spec.SecretFormat.PasswordPolicyName + "/generate")
                if err != nil {
                        return err
                } else {
                        if response.Data != nil {   /**   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< **/
                                d.Spec.calculatedSecret = response.Data["password"].(string)   
                        } else {
                                return errors.New("no data returned by password policy")
                        }
                        return nil
                }
        }
```

I suspect that I'm perhaps hitting a race: in this setup the Vault policy is being created by a resource created at the same time as the RandomSecret -- perhaps the operator is processing the RandomSecret before the policy has been created

the details are at https://gitlab.com/sylva-projects/sylva-core/-/issues/321


(if you think this is a new/different issue, please tell me, I'll open a new one)

**Comment by tmmorin** [comment]
it is explained [here](https://github.com/hashicorp/vault/issues/8361)  that `vaultClient.Logical().Read` can return `nil`

I think that this is what is happening in the panics calls that I see
